// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK1UQ92oVLq-WRY4rC3eJ4D53REsRyXRg',
    appId: '1:364168663175:web:57b746bf5579e310116822',
    messagingSenderId: '364168663175',
    projectId: 'flipmark-f1165',
    authDomain: 'flipmark-f1165.firebaseapp.com',
    storageBucket: 'flipmark-f1165.firebasestorage.app',
    measurementId: 'G-GEV9L09XCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKbCAIQ_XTo_HwTaE8JU1aAA9TxuUOog',
    appId: '1:364168663175:android:507b62ee3642d598116822',
    messagingSenderId: '364168663175',
    projectId: 'flipmark-f1165',
    storageBucket: 'flipmark-f1165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm2U7KDx-FwpDLZ3nUaOML3YBHxTCVkk0',
    appId: '1:364168663175:ios:518b698fe96d449e116822',
    messagingSenderId: '364168663175',
    projectId: 'flipmark-f1165',
    storageBucket: 'flipmark-f1165.firebasestorage.app',
    iosBundleId: 'com.example.flipmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm2U7KDx-FwpDLZ3nUaOML3YBHxTCVkk0',
    appId: '1:364168663175:ios:518b698fe96d449e116822',
    messagingSenderId: '364168663175',
    projectId: 'flipmark-f1165',
    storageBucket: 'flipmark-f1165.firebasestorage.app',
    iosBundleId: 'com.example.flipmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK1UQ92oVLq-WRY4rC3eJ4D53REsRyXRg',
    appId: '1:364168663175:web:0d2f109cef970a55116822',
    messagingSenderId: '364168663175',
    projectId: 'flipmark-f1165',
    authDomain: 'flipmark-f1165.firebaseapp.com',
    storageBucket: 'flipmark-f1165.firebasestorage.app',
    measurementId: 'G-TCRG6G2932',
  );
}
